baseURL: "rizkyramadhana26.github.io" 
title: Rizky
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
        - name: Portofolio
          url: portofolio/
        - name: News
          url: news/

params:
    description: "I am a first-year Computer Science M.S. student at the Virginia Tech advised by <a href='https://people.cs.vt.edu/penggao/'>Prof. Peng Gao</a>. My research focuses in programmable in-network security with P4 switches. Previously, I was an intern at three Indonesian companies, mostly focused on extracting, manage, and produce insight with data."
    author: Rizky Ramadhana Putra Kusnaryanto (Rizky; rizkē)
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rizky Ramadhana Putra Kusnaryanto (Rizky; rizkē)
          subtitle: "I am a first-year Computer Science M.S. student at the Virginia Tech advised by <a href='https://people.cs.vt.edu/penggao/'>Prof. Peng Gao</a>. My research focuses in programmable in-network security with P4 switches. Previously, I was an intern at three Indonesian companies, mostly focused on extracting, manage, and produce insight with data."
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Moritz-Maria von Igelfeld
          buttons:
            - name: CV
              url: cv/
            - name: Portofolio
              url: portofolio/
            - name: News
              url: news/

    socialIcons:
        - name: Email
          url: mailto:rizky@vt.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/rizky-ramadhana-putra-kusnaryanto-6037a51aa/
        - name: GitHub
          url: https://github.com/rizkyramadhana26
        - name: LeetCode
          url: https://leetcode.com/u/rizkyramadhana26/
        - name: YouTube
          url: https://www.youtube.com/@RizkyRamadhana26/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rizky Ramadhana Putra Kusnaryanto"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2